# -*- coding: utf-8 -*-
"""建立向量資料庫.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmMDfGvqxOm8RYL1C-4wnc8okmD6O8KH

### 1. 建立資料夾
"""

from google.colab import files
uploaded = files.upload()

!unzip -o rag_all_chunks.zip -d ./unzipped_chunks

import os
upload_dir = "uploaded_docs"
os.makedirs(upload_dir, exist_ok=True)
print(f"請將你的 .txt, .pdf, .docx 檔案放到這個資料夾中： {upload_dir}")

!mv unzipped_chunks/rag_chunk_*.jsonl uploaded_docs/

"""### 2. 更新必要套件並引入"""

!pip install -U langchain langchain-community pypdf python-docx sentence-transformers faiss-cpu jq

from langchain_community.document_loaders import TextLoader, PyPDFLoader, UnstructuredWordDocumentLoader, JSONLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS

"""### 3. 依 e5 建議加入

自訂支援 E5 的 embedding 模型（加上 "passage:" / "query:" 前綴）
"""

from langchain.embeddings import HuggingFaceEmbeddings

class CustomE5Embedding(HuggingFaceEmbeddings):
    def embed_documents(self, texts):
        texts = [f"passage: {t}" for t in texts]
        return super().embed_documents(texts)

    def embed_query(self, text):
        return super().embed_query(f"query: {text}")

"""### 4. 載入文件

### 5. 建立向量資料庫
"""

splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
split_docs = splitter.split_documents(documents)

embedding_model = CustomE5Embedding(model_name="intfloat/multilingual-e5-small")
vectorstore = FAISS.from_documents(split_docs, embedding_model)

from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.docstore.document import Document
from tqdm import tqdm

# 初始化向量庫（第一批）
batch_size = 2000
vectorstore = None

embedding_model = CustomE5Embedding(model_name="intfloat/multilingual-e5-small")

for i in tqdm(range(0, len(split_docs), batch_size), desc="分批處理中"):
    batch = split_docs[i:i+batch_size]

    if not batch:
        continue

    if vectorstore is None:
        # 第一批初始化
        vectorstore = FAISS.from_documents(batch, embedding_model)
    else:
        # 追加嵌入資料
        vectorstore.add_documents(batch)

# 最後儲存
vectorstore.save_local("faiss_db")
print("✅ 向量資料庫已完成並儲存至 faiss_db/")

"""### 6. 儲存向量資料庫"""

vectorstore.save_local("faiss_db")

!zip -r faiss_db.zip faiss_db

print("✅ 壓縮好的向量資料庫已儲存為 'faiss_db.zip'，請下載此檔案備份。")

from google.colab import files
files.download("faiss_db.zip")

folder_path = upload_dir
documents = []
for file in os.listdir(folder_path):
    path = os.path.join(folder_path, file)
    if file.endswith(".txt"):
        loader = TextLoader(path)
    elif file.endswith(".pdf"):
        loader = PyPDFLoader(path)
    elif file.endswith(".docx"):
        loader = UnstructuredWordDocumentLoader(path)
    elif file.endswith(".jsonl"):
        # ✅ 新增處理 JSONL：只抓 document 欄位
        loader = JSONLoader(file_path=path, jq_schema=".document", text_content=False, json_lines=True)
    else:
        continue
    documents.extend(loader.load())